main: com.winthier.freehat.FreeHatPlugin
name: FreeHat
version: 0.1
api-version: 1.13
description: FreeHat Plugin
author: StarTux
website: https://cavetale.com
depend: []
softdepend: []
commands:
  hat:
    aliases: []
    description: FreeHat Command
    permission: freehat.hat
    usage: /hat
permissions:
  freehat.hat:
    description: Use /freehat
    default: op
  freehat.click:
    description: Put on a hat via click
    default: op
